modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "clovergoshadow"
version = "1.0.0"
displayName = "CloverGoShadow"
displayURL = "https://github.com/CloverCard"
credits = "https://github.com/CloverCard"
authors = "https://github.com/CloverCard"
description = '''
Implements Pokemon Go inspired Shadow Pokemon into Pixelmon
'''

[[dependencies.clovergoshadow]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clovergoshadow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"


[[dependencies.clovergoshadow]]
modId = "pixelmon"
mandatory = true
versionRange = "[9.1.6,)"
ordering = "NONE"
side = "BOTH"
